f = open("blogs_2_tumbl","r")
g = open("tumbl_ide","w")
g.write('')
g.close()
g = open("tumbl_ide","a")

for urls in f:
    g.write("<tr>\n")
    g.write("	<td>open</td>\n")
    g.write("	<td>"+urls+"ask</td>\n")
    g.write("	<td></td>\n")
    g.write("</tr>\n")
    g.write("<tr>\n")
    g.write("	<td>click</td>\n")
    g.write("	<td>id=question</td>\n")
    g.write("	<td></td>\n")
    g.write("</tr>\n")
    g.write("<tr>\n")
    g.write("	<td>type</td>\n")
    g.write("	<td>can we be friends?</td>\n")
    g.write("	<td></td>\n")
    g.write("</tr>\n")
    g.write("<tr>\n")
    g.write("	<td>click</td>\n")
    g.write("	<td>id=ask_button</td>\n")
    g.write("	<td></td>\n")
    g.write("</tr>\n")

